### ISSUE TITLE
ambiguation between flask.request and six.urllib.request

### ISSUE THREAD

**Issue by bramjochems** [mardix/flask-cloudy#19]
[Edited after some further investigations from my end]

I have copied the example code more or less verbatim, but have an issue when downloading files; I then get the error message:

builtins.AttributeError
AttributeError: module 'six.moves.urllib.request' has no attribute 'args'

the issue seems to be in line 421 of flask_cloudy.py:

dl = request.args.get("dl")

The issue here seems that the request object here refers to the request object imported from six.moves.urllib rather than the flask.request object.

Created a pull request that I believe would fix this

**Comment by DuncanBetts** [comment]
I encountered the same error message you mention above, thanks very much for this 👍 .
The issue for me arose whilst using the python:2.7-slim Docker image with flask 0.12 (mentioning this incase you have need to reproduce it).

I'm currently copying the revised file straight into the installation pip carries out inside a Docker container, not ideal but pip doesn't seem to allow installation from specific git commits (and besides, I would have to add git to the container). I'm sure there's a better way but it was the quickest solution.

Hoping this will be pushed to pip before I submit my project in a week or two!

Whilst I'm writing here, thank you mardix very much for this extension, it's great :).

**Comment by mardix** [comment]
Ok thank you folks

@bramjochems  I'm going to check on the pull request. 

Thanks @DuncanBetts

**Comment by bramjochems** [comment]
Thanks for accepting
