### ISSUE TITLE
flask_cloudy.InvalidExtensionError

### ISSUE THREAD

**Issue by raoasifraza11** [mardix/flask-cloudy#24]
Problem:
     I got an error `flask_cloudy.InvalidExtensionError`
I try:
```
f = request.files.get("myfile")
my_upload = storage.upload(f, extension=['fa'])
```

```
f = request.files.get("myfile")
my_upload = storage.upload(f, extension=['.fa'])
```

Can anyone guide me what is the way of adding extention.

**Comment by acnebs** [comment]
You have forgotten an `s`. The kwarg for specifying an extension is `extensions`.

**Comment by mardix** [comment]
Thank you @acnebs
